HEADING_NORTH = "N"
HEADING_SOUTH = "S"
HEADING_WEST = "W"
HEADING_EAST = "E"

DIRECTIONS = [
    HEADING_NORTH,
    HEADING_EAST,
    HEADING_SOUTH,
    HEADING_WEST
]

ACTION_LEFT = "L"
ACTION_RIGHT = "R"
ACTION_MOVE = "M"
